"""Add raccolte, raccolta_parcelle, lotti_olio

Revision ID: 0aadcc232938
Revises: a2dbc72597e7
Create Date: 2026-03-01 21:06:22.552001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aadcc232938'
down_revision: Union[str, None] = 'a2dbc72597e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
