"""Add kg_olio to lotti_olio

Revision ID: 12202f82918e
Revises: 0aadcc232938
Create Date: 2026-03-01 21:49:48.164385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12202f82918e'
down_revision: Union[str, None] = '0aadcc232938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lotti_olio', sa.Column('kg_olio', sa.Numeric(precision=8, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lotti_olio', 'kg_olio')
    # ### end Alembic commands ###
