"""add_movimenti_magazzino_table

Revision ID: 313b17527a8e
Revises: c0e37b12b63a
Create Date: 2026-03-02 23:48:56.905066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '313b17527a8e'
down_revision: Union[str, None] = 'c0e37b12b63a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimenti_magazzino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codice', sa.String(length=20), nullable=False),
    sa.Column('confezionamento_id', sa.Integer(), nullable=False),
    sa.Column('tipo_movimento', sa.String(length=10), nullable=False),
    sa.Column('causale', sa.String(length=20), nullable=False),
    sa.Column('quantita', sa.Integer(), nullable=False),
    sa.Column('data_movimento', sa.Date(), nullable=False),
    sa.Column('anno_campagna', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('riferimento_documento', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clienti.id'], ),
    sa.ForeignKeyConstraint(['confezionamento_id'], ['confezionamenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimenti_magazzino_anno_campagna'), 'movimenti_magazzino', ['anno_campagna'], unique=False)
    op.create_index(op.f('ix_movimenti_magazzino_codice'), 'movimenti_magazzino', ['codice'], unique=True)
    op.create_index(op.f('ix_movimenti_magazzino_id'), 'movimenti_magazzino', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimenti_magazzino_id'), table_name='movimenti_magazzino')
    op.drop_index(op.f('ix_movimenti_magazzino_codice'), table_name='movimenti_magazzino')
    op.drop_index(op.f('ix_movimenti_magazzino_anno_campagna'), table_name='movimenti_magazzino')
    op.drop_table('movimenti_magazzino')
    # ### end Alembic commands ###
