"""partita_iva da 11 a 13 caratteri

Revision ID: 4aa7e85d7438
Revises: b7a2e3c4d5f6
Create Date: 2026-03-03 15:42:59.501217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aa7e85d7438'
down_revision: Union[str, None] = 'b7a2e3c4d5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clienti', 'partita_iva',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=13),
               existing_nullable=True)
    op.alter_column('fornitori', 'partita_iva',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=13),
               existing_nullable=True)
    op.create_index(op.f('ix_vendita_righe_id'), 'vendita_righe', ['id'], unique=False)
    op.create_index(op.f('ix_vendite_id'), 'vendite', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendite_id'), table_name='vendite')
    op.drop_index(op.f('ix_vendita_righe_id'), table_name='vendita_righe')
    op.alter_column('fornitori', 'partita_iva',
               existing_type=sa.String(length=13),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)
    op.alter_column('clienti', 'partita_iva',
               existing_type=sa.String(length=13),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)
    # ### end Alembic commands ###
