"""Initial: users + parcelle

Revision ID: a2dbc72597e7
Revises: 
Create Date: 2026-03-01 20:26:57.852077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2dbc72597e7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcelle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codice', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('superficie_ettari', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('varieta_principale', sa.String(length=100), nullable=False),
    sa.Column('varieta_secondaria', sa.String(length=100), nullable=True),
    sa.Column('num_piante', sa.Integer(), nullable=False),
    sa.Column('anno_impianto', sa.Integer(), nullable=True),
    sa.Column('sistema_irrigazione', sa.String(length=50), nullable=True),
    sa.Column('tipo_terreno', sa.String(length=50), nullable=True),
    sa.Column('esposizione', sa.String(length=20), nullable=True),
    sa.Column('altitudine_m', sa.Integer(), nullable=True),
    sa.Column('stato', sa.String(length=20), server_default='produttivo', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcelle_codice'), 'parcelle', ['codice'], unique=True)
    op.create_index(op.f('ix_parcelle_id'), 'parcelle', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_parcelle_id'), table_name='parcelle')
    op.drop_index(op.f('ix_parcelle_codice'), table_name='parcelle')
    op.drop_table('parcelle')
    # ### end Alembic commands ###
