"""add_documento_to_costi

Revision ID: c0e37b12b63a
Revises: e821ebd6fb9d
Create Date: 2026-03-02 19:32:38.468605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0e37b12b63a'
down_revision: Union[str, None] = 'e821ebd6fb9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('costi', sa.Column('documento', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('costi', 'documento')
    # ### end Alembic commands ###
