"""add categorie_costo and costi tables

Revision ID: e821ebd6fb9d
Revises: a3794119b868
Create Date: 2026-03-02 15:24:51.295971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e821ebd6fb9d'
down_revision: Union[str, None] = 'a3794119b868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
